# automatically generated by the FlatBuffers compiler, do not modify

# namespace: TrainingData

import flatbuffers

class TrainingSet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTrainingSet(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrainingSet()
        x.Init(buf, n + offset)
        return x

    # TrainingSet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrainingSet
    def Dataset(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Example import Example
            obj = Example()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrainingSet
    def DatasetLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def TrainingSetStart(builder): builder.StartObject(1)
def TrainingSetAddDataset(builder, dataset): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dataset), 0)
def TrainingSetStartDatasetVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TrainingSetEnd(builder): return builder.EndObject()
