# automatically generated by the FlatBuffers compiler, do not modify

# namespace: TrainingData

import flatbuffers

class Example(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsExample(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Example()
        x.Init(buf, n + offset)
        return x

    # Example
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Example
    def Input(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Example
    def InputLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Example
    def Output(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Example
    def OutputLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ExampleStart(builder): builder.StartObject(2)
def ExampleAddInput(builder, input): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(input), 0)
def ExampleStartInputVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ExampleAddOutput(builder, output): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(output), 0)
def ExampleStartOutputVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ExampleEnd(builder): return builder.EndObject()
